# Generated by Django 5.1.1 on 2024-09-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('target_date', models.DateTimeField(blank=True, null=True, verbose_name='target date')),
                ('status', models.CharField(choices=[('created', 'created'), ('assigned', 'assigned'), ('complete', 'complete'), ('paused', 'paused'), ('cancelled', 'cancelled')], default='created', verbose_name='task status')),
                ('urgency', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', verbose_name='urgency')),
                ('importance', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', verbose_name='importance')),
                ('is_active', models.BooleanField(default=True, verbose_name='task activity')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='executor')),
                ('parent_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='parent_task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('name', 'employee', 'target_date', 'status', 'urgency', 'importance'),
            },
        ),
    ]
